### 配置项目启动端口号
server:
  port: 9999
spring:
### 项目应用名
  application:
    name: itrip-eureka-server
### 配置Eureka Server端的相关信息
eureka:
  instance:
### 配置Eureka ever的IP地址别名
    hostname: localhost
  client:
### 由于是本项目是作为Eureka Server端存在，因此不需要将本项目的应用注册到注册中心
    register-with-eureka: false
### 整个项目只有一个注册中心，不需要去其它注册中心发现项目，因此关闭其它注册中心发现项目的功能
    fetch-registry: false
### 设置注册中心注册地址
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka